### ISSUE TITLE
problem with latest Studio versions

### ISSUE THREAD

**Issue by rbuikman** [WoodWing/interactive-components-samples#16]
Dear WW,

Seems like there is a problem somewhere.

In Studio (ContentStation), in a digital article with your GoogleMaps example component:
- when you click the 'GOOGLE MAPS' component and then the button 'Edit map' in the right panel (Component Properties), you get the 'Edit interactive component' dialog... 

However, it never gets to the editLink uri while a JavaScript error occurred:

**ERROR TypeError: this.iframe is undefined**
    ngAfterViewInit http://localhost/Enterprise10/contentstation/csde/scripts.87bd645d2962f3a1e7dc.js:16

More info:
After this error, when you close the 'Edit interactive component' dialog and then click 'Edit map' again... suddenly works...

Best regards,

Rene

**Comment by wwjhu** [comment]
This turns out to be a problem in Studio. I created bug CSH-7755 for it and it will be fixed in 11.78.

Thanks for reporting!
